-- Find Total Customers by country
SELECT DISTINCT 
	country AS Countries,
	COUNT(customer_key) AS Total_Customer_Count
FROM gold.dim_customers
Group by country
Order by COUNT(customer_key) DESC

-- Find total customers by Gender
SELECT DISTINCT 
	gender AS Genders,
	COUNT(gender) AS Total_Gender_Count
FROM gold.dim_customers
Group by gender
Order by COUNT(gender) DESC

-- Find the total products by category
SELECT DISTINCT 
	category AS Category,
	COUNT(category) AS Total_Category_Count
FROM gold.dim_products
Group by category
Order by COUNT(category) DESC

--What is the total revenue generated For Each Category

SELECT
	category,
	SUM(sales_amount) AS Total_revenue
FROM
(
SELECT
	f.product_key AS product_key,
	p.category AS category,
	f.sales_amount AS sales_amount
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key)t
GROUP BY category
ORDER BY Total_revenue DESC

--Total Revenue is generated by each customer

SELECT
	c.customer_key AS customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount)AS sales_amount
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key=f.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY sales_amount DESC
--What is the distribution of Sold items accross countries?

SELECT
	c.country AS Country,
	SUM(f.quantity) AS Total_Sold_items
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY SUM(f.sales_amount) DESC

--Total Sales By Country

SELECT 
	c.customer_key AS customer_key,
	c.first_name,
	c.last_name,
	c.country,
	SUM(f.sales_amount)AS sales_amount
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key=f.customer_key
GROUP BY c.country,
c.customer_key,
c.first_name,
c.last_name
ORDER BY sales_amount DESC

--Average Price By Product

SELECT 
	p.product_name,
	f.product_key,
	AVG(price) AS Avg_Price
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY p.product_name,f.product_key
ORDER BY Avg_Price DESC
